#!/bin/bash

set -e

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:{{ user_yum_root_dir }}/usr/lib:{{ user_yum_root_dir }}/usr/lib64"

echo "Create ISO image from web root"
{{ user_yum_bin_path }}/genisoimage -o {{ htdocs_iso_name }} /var/www/virtual/{{ ansible_user_id }}/html

echo "Cloning disk image so it's clean on every boot"
cp "{{ drive_c_img_name }}" "{{ drive_c_active_img_name }}"

{{ user_bin }}/qemu-system-i386 \
    -hda "{{ drive_c_active_img_name }}" \
    -cdrom {{ htdocs_iso_name }} \
    -boot c \
    -cpu pentium \
    -rtc base=localtime,clock=rt,driftfix=slew \
    -m {{ vm_memory_mb }} \
    -vnc :{{ vnc_display}} \
    -net nic,model=pcnet -net user,hostfwd=tcp::{{ outer_port }}-:{{ inner_port }}
